# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: WinFsp.WinFsp
PackageVersion: 2.1.24255
PackageLocale: en-US
Publisher: Navimatics LLC
PublisherUrl: https://github.com/winfsp
PublisherSupportUrl: https://github.com/winfsp/winfsp/issues
PackageName: WinFsp 2023
PackageUrl: https://winfsp.dev/
License: GPLv3
LicenseUrl: https://github.com/winfsp/winfsp/blob/master/License.txt
Copyright: Copyright (C) Bill Zissimopoulos
CopyrightUrl: https://github.com/winfsp/winfsp/blob/master/License.txt
ShortDescription: Windows File System Proxy - FUSE for Windows
Description: |-
  WinFsp enables developers to write their own file systems (i.e. "Windows drives") as user mode programs and without any knowledge of Windows kernel programming.
  It is similar to FUSE (Filesystem in Userspace) for Linux and other UNIX-like computers.
Tags:
- sshfs
- winfsp
ReleaseNotesUrl: https://github.com/winfsp/winfsp/releases/tag/v2.1B2
ManifestType: defaultLocale
ManifestVersion: 1.6.0
